### ISSUE TITLE
main.min.js not in /dist/js folder

### ISSUE THREAD

**Issue by j9t** [blinkkcode/amagaki-starter#2]
Pardon the drive-by issue report:

https://github.com/blinkkcode/amagaki-starter/blob/experimental/views/base.njk assumes a /dist/js/main.min.js file. It seems that this is the expected location for https://github.com/blinkkcode/amagaki-starter/blob/experimental/src/ts/main.ts. There ends up being only a file at /dist/main.js, then.

(I could not immediately find a solution, hence reporting.)

**Comment by jeremydw** [comment]
Latest version adds the required webpack commands to generate `/dist/js/main.min.js` from `/src/ts/main.ts`

Tested:
```
npm run build:src -> builds sources in dev mode
npm run build:src:prod -> builds sources in prod mode
npm run build -> builds sources and amagaki site
```
