### ISSUE TITLE
Sample style sheets are uncompressed

### ISSUE THREAD

**Issue by j9t** [blinkkcode/amagaki-starter#3]
Another drive-by report:

The /dist/css/*.min.css files suggest minified output. The style sheets all seem processed but uncompressed. Am I missing something or should these indeed be minified?

**Comment by jeremydw** [comment]
There's probably a Sass compiler option that can be used to compress whitespace:
https://github.com/blinkkcode/amagaki-starter/blob/experimental/webpack.config.js#L19

That said I'm not sure how much it will help in practice; any server worth its salt should be gzipping the content so any repeating whitespace should likely be compressed over the wire. That said I think it's still a good thing for our starter to have so why not. :)

**Comment by j9t** [comment]
Maybe I miss something else, but why not export the style sheets as foo.css then? It’s probably the “.min” that this is exported to by default that’s confusing then.

**Comment by jeremydw** [comment]
This was fixed with the addition of our `production` webpack rule. Now, when `npm run build` is invoked, the prod build is run, and the generated CSS files are fully minified.

https://github.com/blinkkcode/amagaki-starter/commit/ca7dab941ed2514d998e5ff5767448f6b0602cea
