### ISSUE TITLE
Improve meta tags

### ISSUE THREAD

**Issue by uxder** [blinkkcode/amagaki-starter#7]
Once localization paths are final, we should add:

```
    <meta name="theme-color" content="#FFFFFF">
     <meta name="referrer" content="no-referrer">
     
    <link rel="alternate" href="..." hreflang="x-default" />
    <link rel="alternate" href="..." hreflang="es" />
    ...
    
    
      <meta property="og:image" content="...">
    <meta property="og:site_name" content="...">
    <meta property="og:title" content="...">
    <meta property="og:description" content="...">
    <meta property="og:locale" content="...">
    <meta property="og:url" content="...">
    <meta property="og:type" content="website">
    
    
    Favicon stuff
```

**Comment by willthomson** [comment]
I have some improvements [here](https://github.com/blinkk/google-food-insecurity/blob/main/views/macros/headMetadata.njk) that I can look at adding back to the starter

**Comment by jeremydw** [comment]
Incorporated the improvements from Will's comment and requirements from the original issue into our page builder: https://github.com/blinkk/amagaki-plugin-page-builder

Tackling addition of page builder here: https://github.com/blinkk/amagaki-starter/issues/20
